### ISSUE TITLE
Switch to `TerraformPluginSDK` framework

### ISSUE THREAD

**Issue by patst** [grafana/crossplane-provider-grafana#107]
I have read the [blob post](https://blog.crossplane.io/new-providers-for-crossplane-donated-by-upbound-bring-up-to-4x-cost-savings/) about performance boost and resource usage decrease  when using the new `TerraformPluginSDK` mode. (see [upjet v1.1.0 release notes](https://github.com/crossplane/upjet/releases) )

If I understand everything correct, it would make sense to use this in the Grafana Provider as well.

A template with the required steps could be the PullRequest for the [Azure Provider](https://github.com/crossplane-contrib/provider-upjet-azure/pull/656)

**Comment by julienduchesne** [comment]
Sounds amazing. Probably fixes https://github.com/grafana/crossplane-provider-grafana/issues/87 as well

**Comment by julienduchesne** [comment]
I will try to implement it this week!

**Comment by julienduchesne** [comment]
It's _slightly_ faster 😆 
![image](https://github.com/grafana/crossplane-provider-grafana/assets/29210090/cc4b349d-761a-43fc-8267-670b378e8cb4)

Released in v0.13.0. Tested on our cluster, runs fine!

**Comment by patst** [comment]
> It's _slightly_ faster 😆 ![image](https://private-user-images.githubusercontent.com/29210090/314609528-cc4b349d-761a-43fc-8267-670b378e8cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTczNzAsIm5iZiI6MTcxMDk1NzA3MCwicGF0aCI6Ii8yOTIxMDA5MC8zMTQ2MDk1MjgtY2M0YjM0OWQtNzYxYS00M2ZjLTgyNjctNjcwYjM3OGU4Y2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE3NTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZDMxNzMyZGMxN2Y4MmZlMDVhYzE0NjVjNTE3OTNmZDMxODMxOWUxZDg0ZjIwYTQ0N2ZlMTFlYTVkMjkwNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1YGnyzIa529av2OmrckV-Cbip37ogckYib-O36N7wIQ)
> 
> Released in v0.13.0. Tested on our cluster, runs fine!

That  is amazing!
Thanks for implementing it!

**Comment by julienduchesne** [comment]
Thank you for pointing it out!
