### ISSUE TITLE
How to create a providerconfig using a secret created by serviceaccounttoken

### ISSUE THREAD

**Issue by rwadk** [grafana/crossplane-provider-grafana#138]
I'm using oss and use an providerconfig with grafana-admin credentials to create a new organization, serviceaccount and serviceaccount token.
Now I'm trying to create an organization specific configprovider using the serviceaccounttoken, but that secret created by the serviceaccounttoken is missing the required URL.

I see that it is todo to add the URL here:
https://github.com/grafana/crossplane-provider-grafana/blob/40ef62a4e9c2acfe3f2cb831150d2b9a63c257c7/config/grafana/config.go#L77

Does anyone have an example on how they patch a secret so it can be used in a new providerconfig?

Thanks :)

**Comment by rwadk** [comment]
This is a duplicate of: https://github.com/grafana/crossplane-provider-grafana/issues/39 but relatated to OSS instead of Cloud.

**Comment by julienduchesne** [comment]
I'm trying to figure out a way to do this. The URL is in the provider config but I'm not sure how I can access this through the resource
