### ISSUE TITLE
Unable to use a custom oncall_url

### ISSUE THREAD

**Issue by azkore** [grafana/crossplane-provider-grafana#20]
We have Grafana Cloud in EU West (Belgium) region. When trying to apply a crossplane resource (for example, EscalationChain), there is an error:

```Message:               apply failed: POST https://oncall-prod-us-central-0.grafana.net/oncall/api/v1/escalation_chains/: 403 {detail: Invalid token.} - the region in the url is the default one.```

With terraform we specify `oncall_url` (https://registry.terraform.io/providers/grafana/grafana/latest/docs#oncall_url) in the provider configuration, like this:

```
provider "grafana" {
  oncall_url = "https://oncall-prod-eu-west-0.grafana.net/oncall/"
  oncall_access_token = "***************************"
}
```

but adding it  to provider credentials has no effect, it seems it's missed from this list: https://github.com/grafana/crossplane-provider-grafana/blob/6b5bc0ae9b970a8f83b31c8eb35d410d7a3e5c06/internal/clients/grafana.go#L68-L76

Is there any workaround to specify a non-default region oncall url?

**Comment by julienduchesne** [comment]
Feel free to open a PR to add it to the list you linked above, I'll be happy to do a release

**Comment by azkore** [comment]
@julienduchesne sure, please take a look: https://github.com/grafana/crossplane-provider-grafana/pull/21
