### ISSUE TITLE
Add teamRef for OnCall Integration

### ISSUE THREAD

**Issue by Neko-Follower** [grafana/crossplane-provider-grafana#207]
### Feature Request

Hi! Thank you for the provider.

I wonder if there a possibility to ref team via name rather than id. This would be a very convenient and cool option.

**Comment by Duologic** [comment]
This is currently not possible, the `grafana_oncall_team` resource is only available as a [data source](https://registry.terraform.io/providers/grafana/grafana/latest/docs/data-sources/oncall_team) in Terraform, afaik upjet can't deal with that today.

**Comment by Duologic** [comment]
upstream feature request here: https://github.com/grafana/terraform-provider-grafana/issues/1003

**Comment by Duologic** [comment]
Until upstream supports this, I'm closing this PR.
