### ISSUE TITLE
Browser Test not available in Check CRD

### ISSUE THREAD

**Issue by tg3rh** [grafana/crossplane-provider-grafana#213]
### Crossplane Version

v1.18.1

### Crossplane Grafana Provider Version

v0.21.0

### Affected Resource(s)

*sm.grafana.crossplane.io/v1alpha1/Check
*package/crds/sm.grafana.crossplane.io_checks.yaml

### Expected Behavior

The browser check is already available in Terraform Grafana: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/synthetic_monitoring_check#nested-schema-for-settings
However, it is not part of the CRD in crossplane. I assume this is a bug as they should have feature parity.

### Actual Behavior

I would assume that you could provide the same configuration as it is available in our terraform provider.

**Comment by Duologic** [comment]
This was added to the TF provider in [v3.14.0](https://github.com/grafana/terraform-provider-grafana/releases/tag/v3.14.0), #210 has also added this to the Crossplane provider, released just now.

Docs: https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.22.0/resources/sm.grafana.crossplane.io/Check/v1alpha1#doc:spec-forProvider-settings-browser
