### ISSUE TITLE
how to pass `X-Disable-Provenance` header to the provisioning api

### ISSUE THREAD

**Issue by cheskayang** [grafana/crossplane-provider-grafana#31]
first of all, thx for offering this provider.
looks like in the tf provider from which is generated, it's possible to set an `X-Disable-Provenance`(see https://registry.terraform.io/providers/grafana/grafana/1.39.0/docs#http_headers) , which will allow writing from UI on the resources provisioned. 

is not clear from the crossplane provider doc, where can this be added? Is it in the auth secret?

**Comment by julienduchesne** [comment]
We're fixing this by adding the `disableProvenance` attribute on alerting resources. In next version, released within the next hour, all resources are done except contact point. That one will come in the version after
