### ISSUE TITLE
Update provider-grafana authorization with ServiceAccount implementation

### ISSUE THREAD

**Issue by blut** [grafana/crossplane-provider-grafana#38]
APIKeys will become deprecated and ServiceAccounts with ServiceAccount Tokens will become the new Authorization flow.
This mechanism is already implemented in Terraform: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/service_account_token

Can we get an update of the provider?

**Comment by julienduchesne** [comment]
This works now and the example has been updated: https://github.com/grafana/crossplane-provider-grafana/blob/main/examples/cloud-stack-chain.yaml
