### ISSUE TITLE
Merging multiple different NotificationPolicies

### ISSUE THREAD

**Issue by b-m-f** [grafana/crossplane-provider-grafana#55]
We have the following use case:

1. Initially created `NotificationPolicy` inside of our cluster
2. New team needs new Lines to be added to this `NotificationPolicy.policy`
3. We do not want to manage the `NotificationPolicy` centrally

Our desired workflow would include a new CRD ( maybe `NotficationPolicyPatch` ?? ) that allows us to specify only a desired addition to the `NotificationPolicy.policy` field.
The provider would then need to made aware of this, and dynamically recreate the `NotificationPolicy.policy` field from the initial state and any additions made in `NotficationPolicyPatch` resources during reconciliation

Would such a feature be desired on this provider?

**Comment by julienduchesne** [comment]
You can now specify notification policies for each alert rule. See the `notificationSettings` of the rule group resource: https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.13.2/resources/alerting.grafana.crossplane.io/RuleGroup/v1alpha1#doc:spec-forProvider-rule-notificationSettings

See https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#configure-notifications-simplified for more info
