### ISSUE TITLE
escape terraform interpolation ${} in rulegroup

### ISSUE THREAD

**Issue by cheskayang** [grafana/crossplane-provider-grafana#97]
Hi grafana team, 

i ran into this error when creating the RuleGroup resource
`Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.`

after some digging, turns out it was caused by having `${}`

example, having this in the model expression
```
"$ErrorsLast24h > ${PercentOfMessagesLast24h}"
```

should be a similar issue to https://github.com/grafana/crossplane-provider-grafana/issues/59
and 

https://github.com/grafana/crossplane-provider-grafana/issues/89

currently bypassing this using $$.  we use the exported rules yaml files (so once get into grafana, it will become $), would be nice to have a fix

**Comment by julienduchesne** [comment]
This should be fixed in v0.13.0!
